recipes:
    mac_os_x:
        - ruby_build
        - rbenv::system
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::enable_full_keyboard_access_for_all_controls
        - osxdefaults::enable_standard_function_keys
        - osxdefaults::disable_auto-correct
        - osxdefaults::tap_to_click
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::save_to_disk_not_to_iCloud_by_default
        - osxdefaults::avoid_creating_ds_store_files_on_network_volumes
        - osxdefaults::disable_auto-correct
        - osxdefaults::expand_save_panel_by_default
        - osxdefaults::finder_new_finder_windows_shows_homefolder
        - osxdefaults::finder_allow_text_selection_in_quick_look
        - osxdefaults::enable_safari_debug_menu
        - osxdefaults::mail_copy_email_addresses_instead_of_names_in_mail
        - mac_os_x::settings
        - mac_os_x::screensaver
        - sudoalt::default
attributes:
    rbenv:
      rubies:
      - name: 2.1.1
    osxdefaults:
       finder:
           preferred_view_style: Nlsv
    mac_os_x:
       settings:
         domain:
           FinderShowRemovableMediaOnDesktop:
               domain: com.apple.finder
               key: ShowRemovableMediaOnDesktop
               value: true
           FinderShowExternalHardDrivesOnDesktop:
               domain: com.apple.finder
               key: ShowExternalHardDrivesOnDesktop
               value: true
           FinderShowHardDrivesOnDesktop:
               domain: com.apple.finder
               key: ShowHardDrivesOnDesktop
               value: false
           FinderShowMountedServersOnDesktop:
               domain: com.apple.finder
               key: ShowMountedServersOnDesktop
               value: false
           DisableSmartQuotes:
               domain: NSGlobalDomain
               key: NSAutomaticQuoteSubstitutionEnabled
               value: false

    authorization:
        sudo:
            users:
                - kholloway
            passwordless: true
            include_sudoers_d: true
    homebrewalt:
        apps:
            - git-extras
            - icu4c
            - coreutils
            - libxml2
            - keychain
            - ctags
            - boot2docker
            - pstree
            - postgresql
            - gsasl
            - the_silver_searcher
            - curl
            - wget
            - iftop
            - tree
            - go
            - htop-osx
            - jq
            - multimarkdown
            - nmap
            - mercurial
            - tmux
            - lynx
            - reattach-to-user-namespace
            - zsh
            - tig
        cask_apps:
            - sourcetree
            - iterm2
            - mou
            - qlmarkdown
            - vagrant
            - chefdk
            - atom
            - filebot
            - macpass
            - licecap
            - chicken
