recipes:
    mac_os_x:
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::enable_full_keyboard_access_for_all_controls
        - osxdefaults::enable_standard_function_keys
        - osxdefaults::disable_auto-correct
        - osxdefaults::tap_to_click
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::save_to_disk_not_to_iCloud_by_default
        - osxdefaults::avoid_creating_ds_store_files_on_network_volumes
        - osxdefaults::disable_auto-correct
        - osxdefaults::expand_save_panel_by_default
attributes:
    osxdefaults:
        finder:
            preferred_view_style: Nlsv
    homebrewalt:
        apps:
            - git-extras
            - icu4c
            - coreutils
            - libxml2
            - keychain
            - ctags
            - boot2docker
            - pstree
            - postgresql
            - gsasl
            - the_silver_searcher
            - curl
            - wget
            - iftop
            - tree
            - go
            - htop-osx
            - jq
            - multimarkdown
            - nmap
            - mercurial
            - tmux
            - lynx
            - reattach-to-user-namespace
            - zsh
            - tig
        cask_apps:
            - sourcetree
            - iterm2
            - mou
            - qlmarkdown
            - vagrant
            - chefdk
            - atom
            - filebot
            - macpass
            - licecap
            - chicken
    authorization:
        sudo:
            users:
                - kholloway
            passwordless: true
            include_sudoers_d: true
