recipes:                                       # Configs are parsed and every list is appended to each other, chef handles order and de-duplication
    global:                                    # Recipes mentioned under "global" are installed for all operating systems (we used to support linux, and may do so in the future)
        - applications::create_var_chef_cache
    mac_os_x:                                  # Recipes mentioned under "mac_os_x" are installed on OSX and OSX Server
        - homebrewalt::default                 # Installs homebrew and homebrew cask and installs all apps mentioned in the homebrewalt:apps and homebrewalt:cask_apps attributes
        - nodejs::default                      # Installs nodejs and installs all nodejs packages mentioned in the nodejs:apps attribute
attributes:
    homebrewalt:
        apps:
            - git
            - icu4c
            - coreutils
            - libxml2
            - keychain
            - ctags
            - boot2docker
            - pstree
            - postgresql
            - gsasl
            - the_silver_searcher
            - curl
            - wget
            - iftop
            - tree
            - go
            - htop-osx
            - jq
            - multimarkdown
            - nmap
            - mercurial
            - tmux
            - lynx
            - reattach-to-user-namespace
            - zsh
            - tig
        cask_apps:
            - google-chrome
            - term2
            - mou
            - qlmarkdown
            - vagrant
            - chefdk
            - atom
            - filebot
            - macpass
            - licecap
            - sourcetree
            - chicken
        cask_fonts:
            - inconsolata
    nodejs:
        apps:
            - bower
